// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectionCreate(arg1:any):Promise<main.H>;

export function ConnectionList():Promise<main.H>;

export function Greet(arg1:string):Promise<string>;
